### ISSUE TITLE
Deployment Application Error

### ISSUE THREAD

**Issue by 1312590** [rocketspacer/roomsy-rooms#2]
Server crash on Heroku

![error](https://cloud.githubusercontent.com/assets/18703107/20822996/9276c19e-b882-11e6-8c43-efdcb11d4d29.JPG)

**Comment by rocketspacer** [comment]
Oh crap, I'll fix it ASAP

**Comment by rocketspacer** [comment]
Status update: Here's the logs on Heroku
![heroku-logs](https://cloud.githubusercontent.com/assets/17026876/20823075/74faf468-b883-11e6-9f40-14bd421eff5c.png)

**Comment by rocketspacer** [comment]
Turns out I didn't add any script to start the server in index.js file! LOL  
Fixed here:  
https://github.com/rocketspacer/roomsy-rooms/commit/a506a50fb890fd30cd6f47e5ffd5a519eadd7396
