### ISSUE TITLE
Can not POST and GET room

### ISSUE THREAD

**Issue by 1312629** [rocketspacer/roomsy-rooms#5]
<img width="1273" alt="screen shot 2016-12-12 at 21 56 59" src="https://cloud.githubusercontent.com/assets/16290131/21109437/a67363f4-c0cb-11e6-8af1-50e19730b927.png">
<img width="1265" alt="screen shot 2016-12-13 at 00 20 24" src="https://cloud.githubusercontent.com/assets/16290131/21109438/a67458c2-c0cb-11e6-8ad2-fc0401a6c44c.png">

**Comment by rocketspacer** [comment]
For rooms/roomtypes, please use the associated endpoints:  
**`/api/rooms`**  
**`/api/roomtypes`**  

From the picture you've shown me, it's clearly you are sending requests to **`/api/`** which is a non-existent endpoint

**Comment by rocketspacer** [comment]
For rooms/roomtypes, please use the associated endpoints:  
**`/api/rooms`**  
**`/api/roomtypes`**  

From the picture you've shown me, it's clearly you are sending requests to **`/api/`** which is a non-existent endpoint.

**Comment by rocketspacer** [comment]
Stop being a noob...
